services:                          # 起動するコンテナの一覧を定義
    demo-app:                      # サービス名(コンテナを識別する名前)
        build: .                   # カレントディレクトリのDockerfileを使ってイメージを作成 (.は、カレントディレクトリ)
        volumes:                   # ホスト(PC)とコンテナの間でファイルを共有(同期)する設定
        - .dockervenv:/src/.venv   # ホストマシンの .dockervenv を、コンテナ内の /src/.venv と同期
        - .:/src                   # ホストマシンのカレントディレクトリ全体をコンテナの /src と同期
        ports:                     # ホストマシンとコンテナの間でポートを接続するための設定
        - 8000:8000                # localhost:8000 へのアクセスを、コンテナの8000番ポートへ転送